---
_min_copier_version: "9"

_subdirectory: "meta-template"

_jinja_extensions:
  - copier_templates_extensions.TemplateExtensionLoader
  - copier/extensions/context.py:ContextUpdater
  - copier/extensions/license.py:LicenseExtension
  - copier/extensions/slugify.py:SlugifyExtension
